version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rify_postgres
    environment:
      POSTGRES_DB: rify_ops
      POSTGRES_USER: rify_user
      POSTGRES_PASSWORD: rify_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rify_user -d rify_ops"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local